pull_request_rules:
  - name: Automatic merge when the pull request has been approved.
    conditions:
      - base=main
      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: squash
  - name: Automatic merge when the pull request is made by SeMiD.
    conditions:
      - base=main
      - author=SeMiD
    actions:
      merge:
        method: squash
